### ISSUE TITLE
About train.py

### ISSUE THREAD

**Issue by FlowerFire7** [ljyflores/simplification-project#1]
I followed the method in your readme.I hope to be able to reproduce your experiment. Then entered 
CUDA_VISIBLE_DEVICES=7 python train.py --dataset asset_full --model bart_xsum --loss_type ul --epochs 10 --batch_size 8 --gradient_ accumulation_steps 8. 
but the following error is displayed.

  File "simplification-project/train.py", line 367, in <module>
    columns_to_remove = list(set(dataset["train"].columns).difference(set(["input_ids", "attention_mask", "labels"])))
AttributeError: 'Dataset' object has no attribute 'columns'

What can I do about it?Please contact me if it's convenient.

**Comment by ljyflores** [comment]
Hi! Apologies for the delay, we're looking into this now — it might be an issue with the version of datasets — we'll get back to you asap!

**Comment by ljyflores** [comment]
Hi @FlowerFire7! We've fixed the error, which was coming both from the `simplification-projects` repo and the installed `loss-library` repository.

Kindly get the repository from here, and follow the updated installation instructions!
https://github.com/yale-nlp/Simplification-Projects
